### ISSUE TITLE
panic: runtime error: index out of range [4] with length 4

### ISSUE THREAD

**Issue by frebib** [cloudflare/pint#384]
```
level=debug msg="Scheduling prometheus query" query="increase(sum without (reason, status) (nzbget_history_status_count)[4h:])" uri=http://server:9090
level=debug msg="Cache hit" key=4ac2fe43a6df450657211f8cf8c7d47775f6b543 query="increase(sum without (reason, status) (nzbget_history_status_count)[4h:])" uri=http://server:9090
level=debug msg="Parsed response" query="increase(sum without (reason, status) (nzbget_history_status_count)[4h:])" series=1 uri=http://server:9090
panic: runtime error: index out of range [4] with length 4

goroutine 109 [running]:
github.com/cloudflare/pint/internal/parser/utils.RemoveConditions({0xc0001df960?, 0xc000cd8fa8?})
	github.com/cloudflare/pint/internal/parser/utils/conditions.go:43 +0x9d2
github.com/cloudflare/pint/internal/parser/utils.RemoveConditions({0xc000cda200?, 0xc0007de0d0?})
	github.com/cloudflare/pint/internal/parser/utils/conditions.go:13 +0x29c
github.com/cloudflare/pint/internal/parser/utils.RemoveConditions({0xc0009f4420?, 0x10e00f0?})
	github.com/cloudflare/pint/internal/parser/utils/conditions.go:17 +0x388
github.com/cloudflare/pint/internal/checks.VectorMatchingCheck.checkNode({0xc000cd9970?}, {0x10e00f0, 0xc00022bf80}, 0xc00082bf40)
	github.com/cloudflare/pint/internal/checks/promql_vector_matching.go:64 +0x5f
github.com/cloudflare/pint/internal/checks.VectorMatchingCheck.Check({0x0?}, {0x10e00f0?, 0xc00022bf80?}, {0x0, 0xc000940840, {{0x0, 0x0}, {0x0, 0x0}, 0x0}}, ...)
	github.com/cloudflare/pint/internal/checks/promql_vector_matching.go:50 +0x145
main.scanWorker({0x10e00f0, 0xc00022bf80}, 0xc000256900?, 0xc000256960?)
```

My config file is
```
prometheus "poseidon" {
  uri      = "http://server:9090"
  timeout  = "60s"
  required = true
}

checks {
  disabled = ["promql/fragile"]
}
```

**Comment by prymitive** [comment]
This is already fixed via https://github.com/cloudflare/pint/pull/380/files#diff-2fb2f8f26860a0b9a74157d63baed166635987ee57bfa3b2e15a44b60e368a36
I'll cut a new release that contains this fix next week

**Comment by prymitive** [comment]
https://github.com/cloudflare/pint/releases/tag/v0.30.0
